### ISSUE TITLE
Add new `TransactionByHash` query

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy#1205]
**_This will be a new query that will require new logic in our domain (see #1203 for context)_**

### Tasks
The following are a set of suggestions for how this problem can be tackled.

- [ ] Identify different groupings of ledger entries that make up a single 
logical transaction

- [ ] Define a minimal version of a new `WalletTransactionSummary` type, with the goal being to communicate pertinent information about a transaction to an end-user e.g.:
   - final amount
   - final fees
   - tx hash
   - tx receipt (preimage, onchain txid etc.)
   - new `TxStatus` type that signals the state of the aggregate transaction
   - etc...

- [ ] Implement translations for each grouping that can take in a list of ledger entries and produce a single `WalletTransactionSummary`. Each translation should be unit-tested. These can live in the `src/domain/wallets` folder

- [ ] Implement the cross-wallet edge case where there is a transfer between wallets for a given account. This can maybe be implemented in the `src/domain/accounts` folder

- [ ] Aggregate all possible groupings (implementations) into a single use-case function in the `src/app` folder

- [ ] Create a new `TransactionByHash` query that takes an `accountId` and returns the aggregated `WalletTransactionSummary` version of a transaction by calling the new use-case function

**Comment by anddddrew** [comment]
I can take this on, you can assign me to this
