### ISSUE TITLE
Add new `TransacionByHash` query

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy#1210]
**_This will be a new query that will require new logic in our domain (see #1203 for context)_**

### Tasks
- [ ] Implement a method that can take a list of (`WalletTransaction`) transactions and produce a single `WalletTransactionSummary` entity. This can live in the `src/domain/wallets` folder. For now we can simply add properties for:
   - a new `TxSummaryStatus` type to show the state of the actual transaction
   - unique input for the transaction (payment hash for ln, or address for onchain, counterparty username for intraledger... see `initiationVia` types)
   - unique output for the transaction (received preimage for ln, txid for onchain, counterparty username for intraledger... see `settlementVia` types)

   **This method should be unit-tested.**

- [ ]  Create a new use-case method in the `src/app` folder that:
   - takes a transaction hash and accountId
   - fetches all the transactions from all wallets for a given account (see new `getTransactionsByWalletIdAndHash` method in ledger service from PR #1200)
   - returns a single `WalletTransactionSummary` entity

- [ ] Create a new `TransactionByHash` query that  returns the aggregated `WalletTransactionSummary` version of a transaction by calling the new use-case method

**Comment by anddddrew** [comment]
I can take this on 👍🏼

**Comment by vindard** [comment]
@anddddrew I'm pausing work on #1200 because I think what we've scoped out here is a [cleaner solution](https://github.com/GaloyMoney/galoy/pull/1200#discussion_r836925672)

You may want to cherry-pick all except the very last commit for what you're building tho as I suspect those might be useful (to be confirmed as you actually work through it).

**Comment by vindard** [comment]
> I can take this on 👍🏼

Update on this, this is still an open issue for anyone wanting to take it on

**Comment by rxbryan** [comment]
@vindard, I will like to work on this issue. Can I get assigned to it.

**Comment by vindard** [comment]
Adding some context here from off-github chats.

---

@rxbryan asks:
I would like a few clarification.

1. What is the new TxSummaryStatus type supposed to include. successful, failed, confirmation times or reversed?
2. Since we are taking a list of WalletTransaction, The "returns a single WalletTransactionSummary entity", would be a list of WalletTransactionSummary. No?

---

@vindard response:

> what the new TxSummaryStatus type supposed to include. successful, failed, confirmation times or reversed?

I think success/pending/failed is fine for now to start with, and we can see if any other statuses emerge as we go along

> Since we are taking a list of WalletTransaction, The "returns a single WalletTransactionSummary entity", would be a list of WalletTransactionSummary. No?

This one's tricky as there's a few ways to go about it. Yes eventually a list of LedgerTransactions ends up becoming a (smaller) list of WalletTransactionSummarys, but even before that we were thinking of that the aggregation function would look like to group like transactions in a LedgerTransaction list and produce a single WalletTransactionSummary from them.

So end-to-end I think it probably looks like:
- Undifferentiated list of LedgerTransactions comes in
- Some aggregation function sorts the list into related groups
- Each related group is passed into a translation function to produce a single WalletTransactionSummary
- All produced WalletTransactionSummarys are brought back together into a (smaller) list

This is still probably a pretty open challenge where we likely can go back and forth on the approach and have the end result eventually emerge though I think
